sudo: required
dist: trusty
language: c
compiler: gcc
os: linux

before_install:
    - sudo apt-get install -qq -y libsystemd-dev

before_script:
    - ./autogen.sh

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - libsystemd-journal-dev
            - valgrind
            - autoconf
            - automake

script:
    - ./configure && make && make distcheck
